export const dict = {
    en:{
        layout:{
            nav_item_1:"Our work",
            nav_item_2:"Achievements",
            nav_item_3:"Services",
            nav_item_4:"Technologies",
            nav_item_5:"Team",
            nav_item_6:"Contact",
            theme_tooltip_1:"Theme",
            lang_tooltip_1:"Language",
            social_tooltip_1:"Facebook",
            social_tooltip_2:"Github",
            social_tooltip_3:"Instagram",
            section_title_1:"profesional team",
            article_title_1:"We just create your dream app",
            article_text_1:"We are your best alternative on software development, with high quality products that shines in intuitive, design, speed and originality.",
            article_action_1:"Let's talk",
            privacy_policy:"Privacy Policy",
            terms_of_use:"Terms of Use",
            rights:"© 2024 Husky Devs. All rights reserved.",
        },
        section_1:{
            section_title:"profesional team",
            article_title:"We just create your dream app",
            article_text:"We are your best alternative on software development, with high quality products that shines in intuitive, design, speed and originality.",
            article_button:"Let's talk"
        },
        section_4: {
            article_title: "Technologies We Have Worked with",
            list_title_1:"Front - end",
            list_item_1_1:"HTML",
            list_item_1_2:"SASS",
            list_item_1_3:"JavaScript",
            list_item_1_4:"React",
            list_item_1_5:"CSS",
            list_item_1_6:"Bootstrap",
            list_item_1_7:"Vue",
            list_item_1_8:"Angular",
            list_title_2:"Back - end",
            list_item_2_1:"Node JS",
            list_item_2_2:"Laravel",
            list_item_2_3:"Django",
            list_item_2_4:"MongoDB",
            list_item_2_5:"PHP",
            list_item_2_6:"Python",
            list_item_2_7:"MySQL",
            list_item_2_8:"Posgress SQL",
        },
        section_5: {
            article_title: "Meet our team",
            article_text: "Our experienced developers and designers are passionate about creating innovative solutions that help businesses grow.",
            team_title_1: "Fullstack Developer",
            team_description_1: "26 years old, Web developer focused on improve everyday. Loving soccer, videogames, coding and cook.",
            team_title_2: "Frontend Developer",
            team_description_2: "26 years old. Systems engineer. Living one day at a time.",
            team_title_3: "Fullstack Developer",
            team_description_3: "Software engineer with a fascination for solving problems and optimizing solutions.",
            team_title_4: "UX / UI designer",
            team_description_4: "I'm always looking for the next game-changing user experience that sparks my curiosity.",
        },
        section_6: {
            section_title: "Contact",
            article_title: "Let's meet today to talk about your project",
            article_image: "Husky’s calling",
            article_text: "A member of our team will be happy to answer your questions and help you.",
            article_button: "Let’s meet"
        },
    },
    es:{
        layout: {
            nav_item_1: "Nuestro trabajo",
            nav_item_2: "Logros",
            nav_item_3: "Servicios",
            nav_item_4: "Tecnologías",
            nav_item_5: "Equipo",
            nav_item_6: "Contacto",
            theme_tooltip_1: "Tema",
            lang_tooltip_1: "Idioma",
            social_tooltip_1: "Facebook",
            social_tooltip_2: "Github",
            social_tooltip_3: "Instagram",
            section_title_1: "equipo profesional",
            article_title_1: "Creamos tu aplicación soñada",
            article_text_1: "Somos tu mejor alternativa en desarrollo de software, con productos de alta calidad que destacan en intuición, diseño, velocidad y originalidad.",
            article_action_1: "Hablemos",
            privacy_policy: "Política de Privacidad",
            terms_of_use: "Términos de Uso",
            rights: "© 2024 Husky Devs. Todos los derechos reservados.",
        },
        section_1: {
            section_title: "equipo profesional",
            article_title: "Creamos tu aplicación soñada",
            article_text: "Somos tu mejor alternativa en desarrollo de software, con productos de alta calidad que destacan en intuición, diseño, velocidad y originalidad.",
            article_button: "Hablemos"
        },
        section_4: {
            article_title: "Tecnologías con las que hemos trabajado",
            list_title_1:"Front - end",
            list_item_1_1:"HTML",
            list_item_1_2:"SASS",
            list_item_1_3:"JavaScript",
            list_item_1_4:"React",
            list_item_1_5:"CSS",
            list_item_1_6:"Bootstrap",
            list_item_1_7:"Vue",
            list_item_1_8:"Angular",
            list_title_2:"Back - end",
            list_item_2_1:"Node JS",
            list_item_2_2:"Laravel",
            list_item_2_3:"Django",
            list_item_2_4:"MongoDB",
            list_item_2_5:"PHP",
            list_item_2_6:"Python",
            list_item_2_7:"MySQL",
            list_item_2_8:"Posgress SQL",
        },   
        section_5: {
            article_title: "Conoce a nuestro equipo",
            article_text: "Nuestros desarrolladores y diseñadores experimentados están apasionados por crear soluciones innovadoras que ayudan a las empresas a crecer.",
            team_title_1: "Desarrollador Fullstack",
            team_description_1: "26 años, desarrollador web enfocado en mejorar cada día. Amante del fútbol, los videojuegos, la programación y la cocina.",
            team_title_2: "Desarrollador Frontend",
            team_description_2: "26 años. Ingeniero de sistemas. Viviendo un día a la vez.",
            team_title_3: "Desarrollador Fullstack",
            team_description_3: "Ingeniero de software con fascinación por resolver problemas y optimizar soluciones.",
            team_title_4: "Diseñador UX / UI",
            team_description_4: "Siempre estoy buscando la próxima experiencia de usuario revolucionaria que despierte mi curiosidad."
        },   
        section_6: {
            section_title: "Contacto",
            article_title: "Reunámonos hoy para hablar sobre tu proyecto",
            article_image: "Llamada del Husky",
            article_text: "Un miembro de nuestro equipo estará encantado de responder tus preguntas y ayudarte.",
            article_button: "Reunámonos"
        }      
    }
}