export const dict = {
    en:{
        layout:{
            nav_item_1:"Our work",
            nav_item_2:"Achievements",
            nav_item_3:"Services",
            nav_item_4:"Technologies",
            nav_item_5:"Team",
            nav_item_6:"Contact",
            theme_tooltip_1:"Theme",
            lang_tooltip_1:"Language",
            social_tooltip_1:"Facebook",
            social_tooltip_2:"Github",
            social_tooltip_3:"Instagram",
            section_title_1:"profesional team",
            article_title_1:"We just create your dream app",
            article_text_1:"We are your best alternative on software development, with high quality products that shines in intuitive, design, speed and originality.",
            article_action_1:"Let's talk",
            privacy_policy:"Privacy Policy",
            terms_of_use:"Terms of Use",
            rights:"© 2024 Husky Devs. All rights reserved.",
        },
    },
    es:{
        layout: {
            nav_item_1: "Nuestro trabajo",
            nav_item_2: "Logros",
            nav_item_3: "Servicios",
            nav_item_4: "Tecnologías",
            nav_item_5: "Equipo",
            nav_item_6: "Contacto",
            theme_tooltip_1: "Tema",
            lang_tooltip_1: "Idioma",
            social_tooltip_1: "Facebook",
            social_tooltip_2: "Github",
            social_tooltip_3: "Instagram",
            section_title_1: "equipo profesional",
            article_title_1: "Creamos tu aplicación soñada",
            article_text_1: "Somos tu mejor alternativa en desarrollo de software, con productos de alta calidad que destacan en intuición, diseño, velocidad y originalidad.",
            article_action_1: "Hablemos",
            privacy_policy: "Política de Privacidad",
            terms_of_use: "Términos de Uso",
            rights: "© 2024 Husky Devs. Todos los derechos reservados.",
        },        
    }
}